services:
  bookshelf:
    image: markbeep/audiobookrequest:1
    restart: unless-stopped
    container_name: audiobookrequest
    environment:
      - PUID=1010
      - PGID=169
      - TZ=Europe/Berlin
    ports:
      - "8000:8000"
    volumes:
      - "/srv/data1tb/.config/audiobookrequest:/config"
      - "/srv/data1tb/data:/data"