services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1117
      - PGID=169
      - TZ=Etc/UTC
    volumes:
      - /srv/data1tb/.config/bazarr:/config
      - /srv/data1tb/data/library/movies:/movies #optional
      - /srv/data1tb/data/library/shows:/shows #optional
    ports:
      - 6767:6767
    restart: unless-stopped