services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=146
      - PGID=169
      - TZ=Etc/UTC
#      - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - /srv/data1tb/.config/jellyfin:/config
      - /srv/data1tb/data/library:/data
    ports:
      - 8096:8096
    restart: unless-stopped