services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=293
      - PGID=169
      - TZ=Europe/Berlin
    volumes:
      - /srv/data1tb/.config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped