services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=274
      - PGID=169
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:sonarr-striptracks
    volumes:
      - /srv/data1tb/.config/sonarr:/config
      - /srv/data1tb/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped